# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import image_qrc, sys

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(503, 546)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 421, 411))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border-image: url(:/image/th.jfif);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(270, 300, 75, 21))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color:rgb(170, 85, 0);\n"
"    border-radius: 10px;\n"
"    color:#ffffff;\n"
"    font-size:15px;\n"
"    font-weight:500;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(0, 0, 0);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(30, 127, 255); */\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(30, 127, 255);\n"
"    border-radius: 10px;\n"
"    color:#ffffff;\n"
"    font-size:15px;\n"
"    font-weight:500;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(180, 181, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(30, 127, 255); */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.Ukuran_2 = QtWidgets.QComboBox(Dialog)
        self.Ukuran_2.setGeometry(QtCore.QRect(50, 190, 291, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Ukuran_2.setFont(font)
        self.Ukuran_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"")
        self.Ukuran_2.setObjectName("Ukuran_2")
        self.Ukuran_2.addItem("")
        self.Ukuran_2.addItem("")
        self.Jenis_Coffe_2 = QtWidgets.QComboBox(Dialog)
        self.Jenis_Coffe_2.setGeometry(QtCore.QRect(50, 150, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Jenis_Coffe_2.setFont(font)
        self.Jenis_Coffe_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"")
        self.Jenis_Coffe_2.setMaxVisibleItems(10)
        self.Jenis_Coffe_2.setObjectName("Jenis_Coffe_2")
        self.Jenis_Coffe_2.addItem("")
        self.Jenis_Coffe_2.addItem("")
        self.Jenis_Coffe_2.addItem("")
        self.Jenis_Coffe_2.addItem("")
        self.Jenis_Coffe_2.addItem("")
        self.Jumlah_2 = QtWidgets.QSpinBox(Dialog)
        self.Jumlah_2.setGeometry(QtCore.QRect(50, 230, 51, 21))
        self.Jumlah_2.setMaximumSize(QtCore.QSize(51, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Jumlah_2.setFont(font)
        self.Jumlah_2.setStyleSheet("background-color:rgba(20, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(205, 118, 132, 255);\n"
"color:rgba(205, 255, 255, 230);\n"
"")
        self.Jumlah_2.setMinimum(1)
        self.Jumlah_2.setMaximum(100)
        self.Jumlah_2.setObjectName("Jumlah_2")
        self.Nama_pelanggan_2 = QtWidgets.QLineEdit(Dialog)
        self.Nama_pelanggan_2.setGeometry(QtCore.QRect(50, 110, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Nama_pelanggan_2.setFont(font)
        self.Nama_pelanggan_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgb(0, 255, 255);\n"
"\n"
"\n"
"")
        self.Nama_pelanggan_2.setText("")
        self.Nama_pelanggan_2.setObjectName("Nama_pelanggan_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "pesan"))
        self.Ukuran_2.setItemText(0, _translate("Dialog", "Small"))
        self.Ukuran_2.setItemText(1, _translate("Dialog", "Large"))
        self.Jenis_Coffe_2.setItemText(0, _translate("Dialog", "Latte"))
        self.Jenis_Coffe_2.setItemText(1, _translate("Dialog", "Cappuccino"))
        self.Jenis_Coffe_2.setItemText(2, _translate("Dialog", "Coffe Vietnam"))
        self.Jenis_Coffe_2.setItemText(3, _translate("Dialog", "Good Day"))
        self.Jenis_Coffe_2.setItemText(4, _translate("Dialog", "Caramel Macchiato"))
        self.Nama_pelanggan_2.setPlaceholderText(_translate("Dialog", "Username"))
import image_qrc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
